[mypy]
python_version = 3.12
strict = True
disable_error_code = no-untyped-call
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-appenv]
strict = False
ignore_errors = True

[mypy-main]
strict = False
ignore_errors = True

[mypy-pytest]
strict = False
ignore_errors = True

[mypy-scripts]
strict = False
ignore_errors = True

[mypy-scripts.*]
strict = False
ignore_errors = True

[mypy-examples]
strict = False
ignore_errors = True

[mypy-examples.*]
strict = False
ignore_errors = True

[mypy-docs]
strict = False
ignore_errors = True

[mypy-docs.*]
strict = False
ignore_errors = True

[mypy-risclog.*.conftest]
strict = False
ignore_missing_imports = True
disable_error_code = import-untyped, attr-defined, no-untyped-def

[mypy-*.tests]
strict = False
ignore_errors = True
disable_error_code = no-untyped-def, no-untyped-call

[mypy-*.tests.*]
strict = False
ignore_errors = True
disable_error_code = no-untyped-def, no-untyped-call

[mypy-risclog.*.api.*.view.*]
allow_untyped_decorators = True
